spring:
  datasource:
      url: jdbc:mysql://localhost:3306/shiro_vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
